[package]
name = "d2rust"
version = "0.0.1"
authors = ["jon"]
edition = "2018"

[dependencies]
d2fileformats = { path = "d2fileformats" }

piston = "0.42"
piston2d-graphics = "0.30"
piston2d-opengl_graphics = "0.59"
pistoncore-glutin_window = "0.54"
mpq = "0.5"